package idc.storyalbum.matcher.tools.annotation_converter.old;

/**
 * Holds the name f the attraction within the region
 *
 * @author ozrad
 */
public enum EAttractionName {

    // insinde_building("insinde_building"),
    buena_vista_street_carthay_circle_lounge("Carthay circle lounge"),
    buena_vista_street_carthay_circle_restaurant("Carthay circle restaurant"),
    buena_vista_street_clarabelles_handscooped_ice_cream("Clarabelles ice cream"),
    buena_vista_street_fiddler_fifer__practical_cafe("Fiddler Fifer cafe"),
    buena_vista_street_mortimers_market("Mortimers market"),
    cars_land_cozy_cone_motel("Cozy cone motel"),
    cars_land_filmores_tastein("Filmores tastein"),
    cars_land_flos_v_cafe("Flos v cafe"),
    condor_flats_taste_pilots_grill("Condor flats grill"),
    hollywood_land_award_wieners("Award wieners"),
    hollywood_land_fairfax_market("Fairfax market"),
    hollywood_land_schmoozies("Schmoozies"),
    hollywood_land_studio_catering_co("Studio catering co"),
    pacific_wharf_cocina_cucamonga_mexican_grill("Cocina grill"),
    pacific_wharf_ghirardelli_soda_fountain_and_chocolate_shop("Ghirardelli chocolate shop"),
    pacific_wharf_lucky_fortune_cookery("Lucky fortune cookery"),
    pacific_wharf_mendocino_terrace_at_the_golden_vine_winery("Mendocino terrace winery"),
    pacific_wharf_pacific_wharf_cafe("Pacific wharf cafe"),
    pacific_wharf_pacific_wharf_distribution_co("Pacific wharf distribution co."),
    pacific_wharf_ritas_baja_blenders("Ritas baja blenders"),
    pacific_wharf_sonoma_terrace_at_the_golden_vine_winery("Sonoma terrace winery"),
    pacific_wharf_wine_country_trattoria_at_the_golden_vine_winery("Wine country trattoria"),
    paradise_pier_ariels_grotto("Ariel's grotto"),
    paradise_pier_bayside_brews("Bayside brews"),
    paradise_pier_boardwalk_pizza__pasta("Boardwalk pizza  pasta"),
    paradise_pier_corn_dog_castle("Corn dog castle"),
    paradise_pier_cove_bar("Cove bar"),
    paradise_pier_paradise_garden_grill("Paradise garden grill"),
    paradise_pier_paradise_pier_ice_cream_company("Paradise pier ice cream"),
    a_bugs_land_fliks_flyers("Fliks flyers"),
    a_bugs_land_francis_ladybug_boogie("Francis ladybug boogie"),
    a_bugs_land_heimlichs_chew_chew_train("Heimlichs chew chew train"),
    a_bugs_land_its_tough_to_be_a_bug("Bugs ride"),
    a_bugs_land_princess_dot_puddle_park("Princess puddle park"),
    a_bugs_land_tuck_and_rolls_driveem_buggies("Tuck and Rolls buggies"),
    buena_vista_street_red_car_trolley("Red car trolley"),
    cars_land_luigis_flying_tires("Luigi's flying tires"),
    cars_land_maters_junkyard_jamboree("Maters junkyard jamboree"),
    cars_land_radiator_springs_racers("Radiator springs racers"),
    condor_flats_soarin_over_california("Soarin over California"),
    disney_california_adventure_hollywood_land_hyperion("Hollywood land hyperion"),
    disney_california_adventure_main_entrance("Adventure main entrance"),
    disney_california_adventure_sunshine_plaza("Sunshine plaza"),
    grizzly_peak_grizzly_river_run("Grizzly river run"),
    grizzly_peak_redwood_creek_challenge_trail("Redwood creek trail"),
    hollywood_land_animation_academy("Animation academy"),
    hollywood_land_character_closeup("Character closeup attraction"),
    hollywood_land_disney_junior_live_on_stage("Disney junior show"),
    hollywood_land_disneys_aladdin_a_musical_spectacular("Aladdin musical"),
    hollywood_land_mad_t_party("Mad tea party"),
    hollywood_land_monsters_inc_mike__sulley_to_the_rescue("Mike Sulley ride"),
    hollywood_land_muppet_vision_d("Muppet vision"),
    hollywood_land_red_car_trolley("Red car trolley"),
    hollywood_land_sorcerers_workshop("Sorcerers workshop"),
    hollywood_land_the_hollywood_backlot_stage("Hollywood backlot stage"),
    hollywood_land_the_twilight_zone_tower_of_terror("Tower of terror"),
    hollywood_land_turtle_talk_with_crush("Turtle talk"),
    pacific_wharf_paradise_pier("Paradise pier"),
    pacific_wharf_the_bakery_tour("Bakery tour"),
    pacific_wharf_walt_disney_imagineering_blue_sky_cellar("Blue sky cellar"),
    paradise_pier_california_screamin("California screamin"),
    paradise_pier_games_of_the_boardwalk("Games of the boardwalk"),
    paradise_pier_golden_zephyr("Golden zephyr"),
    paradise_pier_goofys_sky_school("Goofy's sky school"),
    paradise_pier_jumpin_jellyfish("Jumpin jellyfish"),
    paradise_pier_king_tritons_carousel("King Triton's carousel"),
    paradise_pier_meet_duffy_the_disney_bear_at_paradise_pier("Meet Duffy attraction"),
    paradise_pier_mickeys_fun_wheel("Mickey's fun wheel"),
    paradise_pier_phineas_and_ferbs_rockin_rollin_dance_party("Phineas and Ferbs dance party"),
    paradise_pier_pixar_play_parade("Pixar play parade"),
    paradise_pier_silly_symphony_swings("Silly symphony swings"),
    paradise_pier_the_little_mermaid_ariels_undersea_adventure("Ariel's undersea adventure"),
    paradise_pier_toy_story_midway_mania("Toy-story midway mania"),
    paradise_pier_world_of_color("World of color"),
    adventureland_bengal_barbecue("Bengal barbecue"),
    adventureland_tiki_juice_bar("Tiki juice bar"),
    critter_country_harbour_galley("Harbour galley"),
    critter_country_hungry_bear_restaurant("Hungry bear restaurant"),
    fantasyland_troubadour_tavern("Troubadour tavern"),
    fantasyland_village_haus_restaurant("Village haus restaurant"),
    frontierland_big_thunder_ranch_barbecue("Big thunder-ranch barbecue"),
    frontierland_rancho_del_zocalo_restaurante("Rancho restaurante"),
    frontierland_river_belle_terrace("River belle terrace"),
    frontierland_stage_door_cafe("Stage door cafe"),
    frontierland_the_golden_horseshoe("Golden horseshoe"),
    main_street_usa_carnation_cafe("Carnation cafe"),
    main_street_usa_gibson_girl_ice_cream_parlor("Bibson ice cream parlor"),
    main_street_usa_jolly_holiday_bakery_cafe("Jolly holiday bakery"),
    main_street_usa_main_street_cone_shop("Cone shop"),
    main_street_usa_plaza_inn("Plaza inn"),
    new_orleans_square_blue_bayou_restaurant("Blue bayou restaurant"),
    new_orleans_square_cafe_orleans("Cafe Orleans"),
    new_orleans_square_french_market_restaurant("French market restaurant"),
    new_orleans_square_royal_street_veranda("Royal street veranda"),
    tomorrowland_redd_rocketts_pizza_port("Redd rocketts pizza"),
    tomorrowland_the_spirit_of_refreshment("Spirit of refreshment"),
    tomorrowland_tomorrowland_terrace("Tomorrowland terrace"),
    adventureland_enchanted_tiki_room("Enchanted tiki room"),
    adventureland_magic_carpet_of_aladin("Magic carpet of Aladin"),
    adventureland_indiana_jones_adventure("Indiana Jones adventure"),
    adventureland_jungle_cruise("Jungle cruise"),
    adventureland_tarzans_treehouse("Tarzans treehouse"),
    critter_country_davy_crocketts_explorer_canoes("Davy Crockett's canoes"),
    critter_country_splash_mountain("Splash mountain"),
    critter_country_the_many_adventures_of_winnie_the_pooh("Winnie the Pooh adventures"),
    disneyland_park_castle_area_anaheim("Castle"),
    disneyland_park_main_entrance("Main entrance"),
    disneyland_park_walt_disney_statue_anaheim("Walt Disney statue"),
    fantasyland_alice_in_wonderland("Fantasyland"),
    fantasyland_bibbidi_bobbidi_boutique("Bibbidi bobbidi boutique"),
    fantasyland_casey_jr_circus_train("Casey jr. circus train"),
    fantasyland_christmas_fantasy_parade("Christmas fantasy parade"),
    fantasyland_disney_princess_fantasy_faire("Princess fantasy faire"),
    fantasyland_dumbo_the_flying_elephant("Dumbo ride"),
    fantasyland_fireworks_at_disneyland_park("Fireworks show"),
    fantasyland_its_a_small_world("It's a small world ride"),
    fantasyland_jedi_training_academy("Jedi training academy"),
    fantasyland_king_arthur_carrousel("King Arthur carrousel"),
    fantasyland_mad_tea_party("Mad tea party"),
    fantasyland_matterhorn_bobsleds("Matterhorn bobsleds"),
    fantasyland_meet_merida_in_fantasyland("Meet Merida place"),
    fantasyland_mickey_and_the_magical_map("Magical map ride"),
    fantasyland_mickeys_soundsational_parade("Mickey's parade"),
    fantasyland_mr_toads_wild_ride("Mr. Toads wild ride"),
    fantasyland_peter_pans_flight("Peter Pan's flight"),
    fantasyland_pinocchios_daring_journey("Pinocchio's daring journey"),
    fantasyland_pixie_hollow("Pixie hollow"),
    fantasyland_sleeping_beauty_castle_walkthrough("Sleeping beauty walkthrough"),
    fantasyland_snow_whites_scary_adventures("Snow white's scary adventures"),
    fantasyland_storybook_land_canal_boats("Storybook canal boats"),
    frontierland_big_thunder_mountain_railroad("Thunder mountain railroad"),
    frontierland_big_thunder_ranch("Big thunder ranch"),
    frontierland_frontierland_shootin_exposition("Frontierland shooting exposition"),
    frontierland_jingle_jangle_jamboree("Jingle jangle jamboree"),
    frontierland_mark_twain_riverboat("Mark twain riverboat"),
    frontierland_pirates_lair_on_tom_sawyer_island("Tom Sawyer island"),
    frontierland_sailing_ship_columbia("Columbia sailing ship"),
    frontierland_the_golden_horseshoe_stage("Golden horseshoe stage"),
    main_street_usa_disneyland_railroad_main_street_vehicles("Main street vehicles"),
    main_street_usa("Main street USA"),
    main_street_usa_fire_engine("Fire engine"),
    main_street_usa_horsedrawn_streetcars("Horsedrawn streetcars"),
    main_street_usa_horseless_carriage("Horseless carriage"),
    main_street_usa_main_street_cinema("Cinema"),
    main_street_usa_omnibus("Omnibus"),
    main_street_usa_the_disney_gallery("Disney gallery"),
    main_street_usa_the_disneyland_story_presenting_great_moments_with_mr_lincoln("Moments with Mr. Lincoln"),
    mickeys_toontown_chip_n_dale_treehouse("Chip'n Dale treehouse"),
    mickeys_toontown_disneyland_railroad("Disneyland railroad"),
    mickeys_toontown_donalds_boat("Donald's boat"),
    mickeys_toontown_gadgets_go_coaster("Gadgets go coaster"),
    mickeys_toontown_goofys_playhouse("Goofys playhouse"),
    toontown_mickeys_house_and_meet_mickey("Mickey's house"),
    mickeys_toontown_minnies_house("Minnie's house"),
    mickeys_toontown_roger_rabbits_car_toon_spin("Roger rabbit's car toon spin"),
    new_orleans_square_disneyland_railroad("New-Orleans railroad"),
    new_orleans_square_fantasmic("Fantasmic"),
    new_orleans_square_haunted_mansion("Haunted mansion"),
    new_orleans_square_pirates_of_the_caribbean("Pirates of the Caribbean"),
    tomorrowland_astro_orbitor("Astro orbitor"),
    tomorrowland_autopia("Autopia"),
    tomorrowland_buzz_lightyear_astro_blasters("Buzz lightyear astro blasters"),
    tomorrowland_captain_eo("Captain eo"),
    tomorrowland_disneyland_monorail("Disneyland monorail"),
    tomorrowland_disneyland_railroad("Tomorrowland railroad"),
    tomorrowland_finding_nemo_submarine_voyage("Nemo submarine voyage"),
    tomorrowland_innoventions("Innoventions"),
    tomorrowland_space_mountain("Space mountain"),
    tomorrowland_star_tours_the_adventures_continue("Star tours"),
    tomorrowland_starcade("Starcade");

    private String value;

    private EAttractionName(String value) {
        this.value = value;
    }
}